name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        type: choice
        description: Manifest Branch
        options:
        - 14.1
        - 14
        - 12.1
        - 11
        - 9.0
        - 8.1
        - 7.1
        - 6.0
        required: true
        default: 12.1
      DEVICE_TREE_URL:
        description: Device Tree URL
        required: true
        default: https://github.com/ThakurRahulSingh/device_cmf_tetris
      DEVICE_TREE_BRANCH:
        description: Device Tree Branch
        required: true
        default: main
      DEVICE_PATH:
        description: Path the device tree should be synced to, relative to source root
        required: true
        default: device/cmf/tetris
      DEVICE_NAME:
        description: Device Name from tree (should match name on twrp_<DEVICE_NAME>.mk)
        required: true
        default: tetris
      BUILD_TARGET:
        type: choice
        description: Partition containing recovery ramdisk
        options:
        - vendor_boot
        - boot
        - recovery
        required: true
        default: vendor_boot
      RECOVERY_INSTALLER:
        description: Include recovery installer zip
        type: boolean
        required: true
        default: false

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest Branch: ${{ inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ inputs.DEVICE_NAME }}"
        echo "Build Target: ${{ inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"
 
    - name: Check Out
      uses: actions/checkout@v4
            
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5
        sudo add-apt-repository universe
        sudo apt -y install libncurses5

    - name: Check Build Tree
      uses: haya14busa/action-cond@v1.2.1
      id: buildtree
      with:
        cond: ${{ inputs.MANIFEST_BRANCH == '11' || inputs.MANIFEST_BRANCH == '12.1' || inputs.MANIFEST_BRANCH == '14' || inputs.MANIFEST_BRANCH == '14.1' }}
        if_true: aosp
        if_false: omni

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-${{ inputs.MANIFEST_BRANCH }}
          
    - name: Repo Sync
      run: |
        repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
      working-directory: workspace

    - name: Clone device tree
      run: |
        git clone ${{ inputs.DEVICE_TREE_URL }} -b ${{ inputs.DEVICE_TREE_BRANCH }} workspace/${{ inputs.DEVICE_PATH }}

    - name: Building recovery (AOSP)
      if: ${{ steps.buildtree.outputs.value == 'aosp' }} 
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make $(tr -d _ <<< ${{ inputs.BUILD_TARGET }})image -j4
      working-directory: workspace

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          workspace/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.img
        name: ${{ inputs.DEVICE_NAME }} TWRP ${{ inputs.MANIFEST_BRANCH }}
        tag_name: ${{ github.run_id }}
        body: |
          Build for CMF Phone 1
          Manifest: ${{ inputs.MANIFEST_BRANCH }}
          Target: ${{ inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
